study_prefix = "iem"

[[stages.file_upload]]
type = "submanifest"
files = ['file_upload.toml']

[[stages.study_population]]
type = "submanifest"
#files = ['study_population.toml']
files = ['study_population_cache.toml'] # << optional cached copy

[[stages.study_variable]]
type = "submanifest"
files = ['study_variable.toml']

[[stages.study_variable_wide]]
type = "submanifest"
files = ['study_variable_wide.toml']

#[[stages.elastic_query]]
#type = "submanifest"
#files = ['elastic_query.toml']

[[stages.elastic_output]]
type = "submanifest"
files = ['elastic_output.toml']

[[stages.cube]]
type = "submanifest"
files = ['cube.toml']