[[actions]]
description = "variable union (bool)"
type = "build:parallel"
files = [
    "athena/iem__cohort_variable_union.sql",
]

[[actions]]
description = "variable union ('dx')"
type = "build:parallel"
files = [
    "athena/iem__cohort_variable_union_dx.sql",
]

[[actions]]
description = "variable wide (bool)"
type = "build:parallel"
files = [
    "athena/iem__cohort_variable_wide.sql",
]

[[actions]]
description = "variable wide ('dx')"
type = "build:parallel"
files = [
    "athena/iem__cohort_variable_wide_dx.sql",
]
